maximum_availability_zones: 5

# Set `ip_blocks` here or export from vpc component
# ip_blocks:
#   local:
#     - 127.0.0.1/32
#
# securityGroups:
#   -
#     rules:
#       -
#         IpProtocol: tcp
#         FromPort: 22
#         ToPort: 22
#     ips:
#       - local
